export const collectionsList = [
    {
      id: 1,
      auth: "CyberGlob Pull",
      title: "Zeno Technician: Paragon",
      tokenSymbol: "/images/brandIcon.png",
      favCout: "2.5K",
      coverImg: "/images/collection3.png",
      authImg: "/images/circle-img.png",
    },
    {
      id: 2,
      auth: "CyberGlob Pull",
      title: "Zeno Technician: Paragon",
      tokenSymbol: "/images/brandIcon.png",
      favCout: "2.5K",
      coverImg: "/images/collection2.png",
      authImg: "/images/circle-img.png",
    },
    {
      id: 3,
      auth: "CyberGlob Pull",
      title: "Zeno Technician: Paragon",
      tokenSymbol: "/images/brandIcon.png",
      favCout: "2.5K",
      coverImg: "/images/collection3.png",
      authImg: "/images/circle-img.png",
    },
    {
      id: 4,
      auth: "CyberGlob Pull",
      title: "Zeno Technician: Paragon",
      tokenSymbol: "/images/brandIcon.png",
      favCout: "2.5K",
      coverImg: "/images/collection4.png",
      authImg: "/images/circle-img.png",
    },
    {
      id: 5,
      auth: "CyberGlob Pull",
      title: "Zeno Technician: Paragon",
      tokenSymbol: "/images/brandIcon.png",
      favCout: "2.5K",
      coverImg: "/images/collection5.png",
      authImg: "/images/circle-img.png",
    },
    {
      id: 6,
      auth: "CyberGlob Pull",
      title: "Zeno Technician: Paragon",
      tokenSymbol: "/images/brandIcon.png",
      favCout: "2.5K",
      coverImg: "/images/collection3.png",
      authImg: "/images/circle-img.png",
    },
    {
      id: 7,
      auth: "CyberGlob Pull",
      title: "Zeno Technician: Paragon",
      tokenSymbol: "/images/brandIcon.png",
      favCout: "2.5K",
      coverImg: "/images/collection2.png",
      authImg: "/images/circle-img.png",
    },
    {
      id: 8,
      auth: "CyberGlob Pull",
      title: "Zeno Technician: Paragon",
      tokenSymbol: "/images/brandIcon.png",
      favCout: "2.5K",
      coverImg: "/images/collection3.png",
      authImg: "/images/circle-img.png",
    },
    {
      id: 9,
      auth: "CyberGlob Pull",
      title: "Zeno Technician: Paragon",
      tokenSymbol: "/images/brandIcon.png",
      favCout: "2.5K",
      coverImg: "/images/collection4.png",
      authImg: "/images/circle-img.png",
    },
    {
      id: 10,
      auth: "CyberGlob Pull",
      title: "Zeno Technician: Paragon",
      tokenSymbol: "/images/brandIcon.png",
      favCout: "2.5K",
      coverImg: "/images/collection5.png",
      authImg: "/images/circle-img.png",
    },
  ];